server:
  port: 8083

spring:
  application:
    name: shipping-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: shipping-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3

logging:
  level:
    com.kafka: DEBUG

kafka:
  topic:
    payed-orders: payed_orders
    sent-orders: sent_orders
    out-of-stock: out_of_stock_orders