server:
  port: 8081

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      retry.backoff.ms: 200

logging:
  level:
    com.kafka: DEBUG

kafka:
  topic:
    new-orders: new_orders